version: '3.8'

name: 'stupid-crab-api'

services:
  db:
    container_name: 'stupid-crab-api-db'
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  myapp:
    container_name: 'stupid-crab-api-app'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'